### ISSUE TITLE
Unable to change PATH to run action in different category

### ISSUE THREAD

**Issue by dududuarte** [repo-sync/pull-request#100]
Im trying to use this action but refering to a different path, a underlying git repository inside of the first one.
To do this I change the env variables of GITHUB_WORKSPACE, RUNNER_WORKSPACE and even GITHUB_REPOSITORY.

Even after forcing this changes the action still referes to checkout/action:
![image](https://user-images.githubusercontent.com/18660810/185657460-f3427b5c-afb9-4f4b-bb92-9192023d83c9.png)

Im kinda confused since [entrypoint.sh](https://github.com/repo-sync/pull-request/blob/master/entrypoint.sh#L26) gives the idea that changing GITHUB_REPOSITORY would be enough

**Comment by wei** [comment]
https://github.com/repo-sync/pull-request/blob/992f4d71681e87fe325632f2ed0eaaf8f08347ef/entrypoint.sh#L26

This line is adding authentication tokens to the remote. More work is needed to make sure actions/checkout checks out the correct repo in the correct path. This use-case is not a supported case therefore we will be closing for now~
