### ISSUE TITLE
Add support for marking the PR as auto-merge

### ISSUE THREAD

**Issue by mmanciop** [repo-sync/pull-request#102]
It'd be lovely to be able to [mark a PR as auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) on creation :-)

**Comment by wei** [comment]
See https://github.com/repo-sync/pull-request/issues/53

**Comment by mmanciop** [comment]
Closing as duplicate of #53
