### ISSUE TITLE
multiline Body not working

### ISSUE THREAD

**Issue by krtschmr** [repo-sync/pull-request#103]
we would like to reference by commit message convention to have related tickets autoclosed

```
      - name: get the PR body
        run: |
          echo "👑 *An automated PR* 👑\n\n" > pr_msg
          git log origin/master..origin/staging --no-merges --pretty='format:%s' > diff
          cat diff | grep -oP '\[#[0-9]{4,5}\]' | grep -v "0000" | grep -oP '\#[0-9]{4,5}' >> pr_msg
          sed -i 's/#/closes #/g' pr_msg
```
⬆️  this works great and produces a file like

```
closes #1234
closes #9854
closes #1235
```

We continue to grab it via actions and then reuse it in the PR Body

```
      - name: Get message
        id: vars
        run: echo ::set-output name=pr_body::$(cat pr_msg)

     ...
          source_branch: ${{ steps.branch.outputs.name }}
          destination_branch: "master"
          pr_title: "🚢 ${{ steps.branch.outputs.name }} - SHIP IT :shipit:"
          pr_body: ${{ steps.vars.outputs.pr_body }}
```

<img width="556" alt="image" src="https://user-images.githubusercontent.com/13366714/192955079-58fd1327-8110-48b0-8c64-cca1853877e5.png">

What would be the _correct way_ of having the new lines respected?

**Comment by wei** [comment]
There is currently an open PR for this https://github.com/repo-sync/pull-request/pull/89

**Comment by krtschmr** [comment]
thanks @wei

**Comment by krtschmr** [comment]
it didn't fixed it.

@wei I forked, merged the PR #89 into our master and used it. the result is this:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/13366714/193209181-2dcbc526-d499-4e1d-850f-3df7953eaff5.png">

**Comment by wei** [comment]
It seems to be working in https://github.com/Telefonica/mistica-icons/blob/8ece560530b0277eb0bd41aaddfc507d9ddf3dae/.github/workflows/figma-export.yml#L284-L286

Can you wrap it with quotes similar to the one in the comment?

**Comment by krtschmr** [comment]
i will give it a try tomorrow!

**Comment by krtschmr** [comment]
i'll try this now . will feedback.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/13366714/199435322-59b3f97d-0f2b-4704-9bd5-3ed0d33bc807.png">

**Comment by krtschmr** [comment]
still not working. 
more details here: https://github.com/repo-sync/pull-request/pull/89#issuecomment-1301282166

**Comment by wei** [comment]
@krtschmr Here is a another simple working example:

Code: https://github.com/wei/test-pr/blob/15f57cc1439fde8185f60a4cd3455c6a0c1a7e1b/.github/workflows/pr.yml#L17-L20
PR: https://github.com/wei/test-pr/pull/11

**Comment by wei** [comment]
Alternatively:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/5880908/199620684-1934aab5-d5ea-48d3-b13e-af4e34f43ce3.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/5880908/199620709-621ec04b-3d70-47a2-a2b7-46df99418d24.png">

**Comment by krtschmr** [comment]
thanks. i didn't know about yaml multiline foo. 
will try now

```
          pr_body: |
            ${{ steps.vars.outputs.pr_body }}
```

**Comment by krtschmr** [comment]
this also doesn't work for us. 
the string itself contains multiple \n but the outcome is still. no matter what syntax on yaml i use.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/13366714/199667986-f5649e33-ce01-45b0-8da3-838dfc3bd099.png">

**Comment by wei** [comment]
As per my screenshot in the last comment, the string needs to contain actual line breaks instead of the text "\n". Can you verify that is the case in the output variable you created?

**Comment by krtschmr** [comment]
then i understand. so we cannot pass strings, containing \n. then this issue is settled. or actually another issue, maybe worth adressing?

**Comment by wei** [comment]
I don't believe this is an issue as it's working as expected from my testing above. 

You just need to pass pr body string containing actual line breaks as seen in the examples I provided.

**Comment by krtschmr** [comment]
i mean, yes, those are line breaks.

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/13366714/199693271-6d110075-f790-4dd0-9aed-93052947fa43.png">

**Comment by krtschmr** [comment]
it's also not really important to us actually.  ruby `puts(array)` does also add new lines and then we have the `closes XZY` just in one line rather than multilines. it still works and creating the PR is awesome 🥳

**Comment by wei** [comment]
Found the root cause as GitHub actions is truncating multiline outputs. 

Also, the way you set output variable is being deprecated. It will likely be fixed once you update how you set your output. 

ref: https://github.com/community/community/discussions/26288#discussioncomment-3876281

and https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by krtschmr** [comment]
allright. i saw the deprecation but never looked into it yet. writing key=valyue into one object sounds way easier. i'll give it a shot in the near future and report back to you. thanks for your effort!
