### ISSUE TITLE
Deprecation Warning Output from GitHub Actions

### ISSUE THREAD

**Issue by vnovacev** [repo-sync/pull-request#104]
**Behaviour**

```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

[https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.com/actions/checkout/issues/url)

**Comment by danielgomezrico** [comment]
I see two warnings:

1. `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: maierj/fastlane-action`

2. `The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Comment by wei** [comment]
set-output has been fixed in #105

**Comment by danielgomezrico** [comment]
How can we use it? Just having this, it will pick this change?

```
      uses: repo-sync/pull-request@v2
```

**Comment by wei** [comment]
@danielgomezrico Correct!
