### ISSUE TITLE
Wildcard in destination_branch

### ISSUE THREAD

**Issue by crengifo** [repo-sync/pull-request#113]
how handle  it if we want use a wilcard or multiple branches as destination to pr? 

Example : destination_branch: "feature/**" or  destination_branch: [develop, main]

**Comment by wei** [comment]
Hi @crengifo thanks for your question! 

You can use matrix builds with a custom variable. See https://stackoverflow.com/questions/59180385/using-an-array-of-values-to-repeat-a-step-in-github-actions-workflow for more info.
