### ISSUE TITLE
Any way to update the existing PR using this action

### ISSUE THREAD

**Issue by vasagirisai** [repo-sync/pull-request#124]
I already created a PR using the action and re-run the workflow , but it is saying PR is already requested .
But i wanted to update , Is there any way ?
And also while creating a PR STD_ERROR=Error creating a pull request : Unprocessable Entity (HTTP422)
can you also let me know how i can overcome this ?

**Comment by wei** [comment]
Currently updating PR is not supported as it could overwrite important information.

The line under `STD_ERROR=Error creating a pull request : Unprocessable Entity (HTTP422)` should indicate a more friendly error message.

**Comment by vasagirisai** [comment]
Sure , thank you and updating PR will be added anytime ?

**Comment by wei** [comment]
It's currently not on the roadmap. If there are popular use-cases we may consider them at a later time.

**Comment by vasagirisai** [comment]
Hope that is one the most required thing , i can also look into that how to
add . Can you help me here ?
