### ISSUE TITLE
Need to understand about docker image usage 

### ISSUE THREAD

**Issue by vasagirisai** [repo-sync/pull-request#128]
I can see there is a use of docker image , may i know why and how this docker image is working ? Never mind this may be the simple one but just wanted to understand the background of it

**Comment by Ebonsignori** [comment]
Not entirely sure what you're asking.

This repo wraps all of the logic needed to accomplish opening a pull request in a Docker image.

This is one of many approaches to writing an action like this. For instance, the logic in the shell file, [entrypoint.sh](https://github.com/repo-sync/pull-request/blob/master/entrypoint.sh) could have been written directly in the [action.yml](https://github.com/repo-sync/pull-request/blob/master/action.yml) file. By instead wrapping the logic in a Dockerfile we get a number of benefits. You can [pull it directly](https://github.com/repo-sync/pull-request#docker-container-image-usage) and also use it in a different context from a GitHub action. You can run it locally, test it, and more on any machine that has Docker setup.

As to how this repo uses Docker:

When you use this action, the entry point for the logic is in [action.yml](https://github.com/repo-sync/pull-request/blob/master/action.yml#L61-L65)

->

Which runs the [Dockerfile](https://github.com/repo-sync/pull-request/blob/master/Dockerfile)

->

Which calls [entrypoint.sh](https://github.com/repo-sync/pull-request/blob/master/entrypoint.sh) and that performs the logic to open the PR

Hope that helps. Recommend Googling for reasons on why to use Docker if you'd like to know more
