### ISSUE TITLE
Pull Request no longer successful

### ISSUE THREAD

**Issue by metalsquad4u** [repo-sync/pull-request#132]
Hi, the pull request is no longer successfully creating a pull request. It is giving the following error in its output,

Retrieving pull request details
  ✖ Pull request command failed. This is the stderr output:
  Error creating pull request: Forbidden (HTTP 403)

**Comment by heiskr** [comment]
Hi @metalsquad4u , thank you for opening an issue. Unfortunately, this isn't enough information for us to be able to help you. I'm closing this issue, but let us know if the problem persists.
