### ISSUE TITLE
Allow Forcing PR Creation When No Files Changed

### ISSUE THREAD

**Issue by TheSench** [repo-sync/pull-request#133]
I have a deployment process that runs based on commits being pushed to a branch.  Occasionally, I need to re-trigger that process by adding a PR with an empty commit (no files changed).  I am trying to automate that process using this action, but it short-circuits due to there being no _file changes_ in my empty commit.

I'd like to have the option to tell the action to force the PR creation, even if no files have changed (I at least have a new commit to merge).

**Comment by TheSench** [comment]
The check is looking at commit hashes, not doing a file-diff between the two commits, so something is going wrong on my side when it is creating the branch.  This action is working as expected.

**Comment by TheSench** [comment]
Nevermind, it actually is doing a file-diff check:
https://github.com/repo-sync/pull-request/blob/master/entrypoint.sh#L108-L113

I would like to be able to specify an option that allows this check to be skipped.

**Comment by heiskr** [comment]
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.
