### ISSUE TITLE
Bug: No longer supports repositories containing periods in their names

### ISSUE THREAD

**Issue by mwaddell** [repo-sync/pull-request#136]
`pull-request` no longer works for any repository whose name contains a period (as of v2.12)

Workarounds:
- Downgrade to v2.11 which still works for these repositories
- Rename the repository to use a hyphen or underscore instead of a period

**Comment by heiskr** [comment]
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.
