### ISSUE TITLE
Action flagged as "error" while it's just doing nothing

### ISSUE THREAD

**Issue by mblotin-ledger** [repo-sync/pull-request#138]
Hello,

We have an automated process that creates pull requests on one of our projects, but since this is a git subtree, sometimes there are no changes in this specific subtree.
I get an email notification each time because the pull request command returns the following error :

```
✖ Pull request command failed. This is the stderr output:
  Aborted: no commits detected between origin/XXXX and YYYYY
```

I see in the code that you already have a condition for "already exists" and not return an error code, could and should an exception be added for the "no commits detected" error ?

**Comment by heiskr** [comment]
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.
