### ISSUE TITLE
pull_request_target not triggered

### ISSUE THREAD

**Issue by reaper** [repo-sync/pull-request#139]
Hi, figured out that other github actions listening for the `pull_request_target` event aren't triggering after the pull request have been created. It works when I create the pull requestion from the web interface. Can you advice ? Thanks!

**Comment by heiskr** [comment]
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.
