### ISSUE TITLE
Looks like "git fetch refs" broken by checkout@v2

### ISSUE THREAD

**Issue by romaninsh** [repo-sync/pull-request#14]
fatal: Refusing to fetch into current branch refs/heads/release/1.0 of non-bare repository
15
##[error]Docker run failed with exit code 128

(git is no longer in detached state, see https://github.com/actions/checkout/releases/tag/v2.0.0)

**Comment by jlambrechts** [comment]
fatal: Refusing to fetch into current branch refs/heads/develop of non-bare repository
##[error]Docker run failed with exit code 128

**Comment by kt3k** [comment]
We saw the same error with checkout@2, and we fixed it by changing `ref` of checkout action like `ref: master` -> `ref: refs/remotes/origin/master`

**Comment by wei** [comment]
can you try
```
- uses: actions/checkout@v2
- run: git fetch
```

**Comment by wei** [comment]
Fixed in #24
