### ISSUE TITLE
Add delete_branch option 

### ISSUE THREAD

**Issue by atheo89** [repo-sync/pull-request#140]
It would be nice to provide the option `delete_branch`  true or false after the pull request is merged. 
Overall, nice work! 
cheers

**Comment by wei** [comment]
Good idea but need to check if such a flag is supported in the cli tool. PR welcome!

**Comment by heiskr** [comment]
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.
