### ISSUE TITLE
Refusing to fetch into current branch [...] of non-bare repository

### ISSUE THREAD

**Issue by ChristophShyper** [repo-sync/pull-request#24]
Hi. I'm getting: `fatal: Refusing to fetch into current branch [...] of non-bare repository`

For clean repository it happens for example when I run `actions/checkout@v2`. Works only for `actions/checkout@v1`.

But when I make some changes to files, want to push it to a new branch and then create pull request from it it's happening again. So basically when current local branch is not equal to `GIT_REF`.

How can this be solved? Any ideas?

**Comment by wei** [comment]
Do you reproduce and provide an example

**Comment by ChristophShyper** [comment]
Second case is something along the lines:
```
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replace
        id: replace
        run: |
          find . -type f -not -path '*/\.*' -print0 | xargs -0 sed -i 's/foo/bar/g'
      - name: bash
        run: |
          git checkout -b testing
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "Changed some files"
          git push origin testing
      - name: Create pull request (conditional)
        uses: repo-sync/pull-request@v2
        with:
          source_branch: testing
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "${{ github.event.commits[0].message }}"
          pr_body: "TESTING"
```

**Comment by wei** [comment]
This should be resolved. Updated docs to use `actions/checkout@v2`.

**Comment by zeke** [comment]
Nice! cc @sarahs
