### ISSUE TITLE
Make silent failure configurable

### ISSUE THREAD

**Issue by alex-pex** [repo-sync/pull-request#28]
https://github.com/repo-sync/pull-request/blob/f4c919173e3787ab31dd2bd247d865721446e36d/entrypoint.sh#L83

The problem with silent failure is I don't know when it ... fails!

please add
`  allow_failure: true` to the configuration, so I can set it to false

**Comment by alex-pex** [comment]
The reason is: in my case the build failed because of an API limit reached, and not because of a duplicate PR

**Comment by wei** [comment]
This is doable but I'm not sure how you're reaching the limit. This action uses `GITHUB_TOKEN` secret specifically to run actions in the repo, does it share the rate limit quota with other tokens?

**Comment by wei** [comment]
Perhaps you can inspect the output of the step variable `pr_url` to determine the success of the PR creation. 

https://github.com/repo-sync/pull-request/blob/f4c919173e3787ab31dd2bd247d865721446e36d/entrypoint.sh#L93

**Comment by wei** [comment]
Closed due to inactivity, please feel free to reopen.
