### ISSUE TITLE
Using title of the original pr

### ISSUE THREAD

**Issue by katelfox** [repo-sync/pull-request#29]
Is it possible to reference the title of the original pr?

I wanted to do something like `        pr_title: "Pulling ${{ pr_title }} into master"`

**Comment by wei** [comment]
Fetching the title of original pr is your responsibility. You can then put it in pr_title like you have it.

**Comment by katelfox** [comment]
@wei can you point me to a doc on how to do this or give me any pointers?

**Comment by wei** [comment]
Sure thing. Could you elaborate on what an "original pr" is and a detailed step by step workflow you're trying to setup?

**Comment by katelfox** [comment]
Goal that I'm trying to accomplish: On a push to a branch create a pr in master.

I've setup your action to run on a push to a branch.  It just happens that the branch is protected and can only have code pushed to it if the pr is approved.  

If I can't get the name of the pr that triggered the push -- it would be good to get at least get the title of the commit that is getting pushed.

Really appreciate your help!

**Comment by wei** [comment]
After actions/checkout you can just run a script to get the pull request title using hub CLI or GitHub CLI and set it as [an environment variable or a step variable](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions) to be used in pr_title. 

Please lmk if you need further clarifications feel free to paste your workflow file for feedback too.  😃
