### ISSUE TITLE
Allow team reviewers

### ISSUE THREAD

**Issue by NeonDaniel** [repo-sync/pull-request#35]
Is it possible to add an option to specify an organization team to the pr_reviewer option?

**Comment by wei** [comment]
We're using hub under the hood which is using GitHub REST API (that is failing). 

I see a bug being discussed at https://github.community/t/codeowners-works-with-users-but-not-teams/733/6?u=wei which you can follow and contact GitHub supoort about. 😃

**Comment by wei** [comment]
Closing for now.

**Comment by poldz123** [comment]
Maybe if you allow Personal access token, you might be able to set the private team.

**Comment by wei** [comment]
@poldz123 did you try it? It is allowed right now. You can add a secret called `PAT` and use `secrets.PAT` in place of `secrets.GITHUB_TOKEN`.

**Comment by poldz123** [comment]
@wei If you are using octokit from github then you can set two type of reviewers. reviewers and team_reviewers. In combination of PAT you will be able to use private teams.

Here is a sample: https://github.com/delivery-much/actions-assigner/blob/master/src/github.js

**Comment by wei** [comment]
@poldz123 Our action uses hub and teamReviewers seem to be supported already. 

https://github.com/github/hub/pull/1652#issuecomment-489143339
