### ISSUE TITLE
fatal: Ambiguous argument 'BRANCH_NAME': both revision and filename

### ISSUE THREAD

**Issue by PabloBarrenechea-Reflektion** [repo-sync/pull-request#42]
Hi @repo-sync! 
Thanks for the action, we are using it and it is helping us a lot.
I found an issue, probably on our end, but I would like to share it anyway. 
We have a folder named prod and a branch also named prod. When we tried to trigger the action we saw that we are getting this error:
 ```
fatal: ambiguous argument 'prod': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
We noticed that adding `--` in the following line https://github.com/repo-sync/pull-request/blob/master/entrypoint.sh#L37 works. 
If you feel like is an issue, i can submit a PR.

Best regards,

Pablo

**Comment by wei** [comment]
Hi @PabloBarrenechea-Reflektion , Thanks for noticing! PR Welcome!

**Comment by PabloBarrenechea-Reflektion** [comment]
Excellent, just submitted!
Keep the awesome job on this repo!
