### ISSUE TITLE
Pure JS imeplementation?

### ISSUE THREAD

**Issue by nstdio** [repo-sync/pull-request#48]
We are using self-hosted runners, and `repo-sync/pull-request@v2` uses Docker image to create a intermediate docker image to run it. After a some period of time we are experiencing storage issues because of intermediate images.

Is it possible to provide a JS implementation, in order to avoid image creation?

**Comment by wei** [comment]
The project depends on `hub` cli at this time.

One thing we could do is referencing a docker image instead of building one each time. Similiar to: https://github.com/repo-sync/github-sync/blob/3832fe8e2be32372e1b3970bbae8e7079edeec88/action.yml#L23-L25

**Comment by wei** [comment]
Added a section to README: [Docker Container Image Usage
](https://github.com/repo-sync/pull-request#docker-container-image-usage)
