### ISSUE TITLE
Is this action compatible with the private repository?

### ISSUE THREAD

**Issue by SharryXu** [repo-sync/pull-request#49]
Hey Guys,

I am using this action on my private repository but it seems there are some errors in the processing like below:

Error creating pull request: Not Found (HTTP 404)
Not Found
Are you sure that github.com/SharryXu/blog exists?

Do you guys have any ideas? Maybe I need to add more options when creating the PAT?

**Comment by wei** [comment]
It should~ Did you check all of `repo` scope when creating PAT? I suggest trying that PAT locally and see if you can clone the repo using `git clone https://<access_token>@github.com/owner/repo.git`

**Comment by SharryXu** [comment]
Hey @wei ,

Thanks for your response and it works. I just created a new token which I applied all repo options.
