### ISSUE TITLE
Pull request number as output

### ISSUE THREAD

**Issue by christhekeele** [repo-sync/pull-request#50]
👋  Hey! Small feature request, it'd be great to be able to get just the created PR number in subsequent steps, instead of just the [url](https://github.com/repo-sync/pull-request/blob/master/action.yml#L46-L47).

**Comment by wei** [comment]
Thanks for the suggestion @christhekeele , PR Welcome!

https://github.com/repo-sync/pull-request/blob/33777245b1aace1a58c87a29c90321aa7a74bd7d/entrypoint.sh#L93-L94

Something like this should work:

```bash
echo "::set-output name=pr_number::${PR_URL##*/}" 
```

**Comment by christhekeele** [comment]
@wei I'd love to contribute if I can find some time! The main barrier to me doing that is testing: I have no idea how to meaningfully test a github action during development (any links to official guides would be appreciated), and there are no tests included with the project so I'm not sure how to begin.

**Comment by wei** [comment]
Thanks @christhekeele you can make the change and use `name/repo#commit-hash` in an action to perform testing.

**Comment by christhekeele** [comment]
Ah clever, thanks
