### ISSUE TITLE
One PR with auto-merge option enabled

### ISSUE THREAD

**Issue by dmitrysimkin** [repo-sync/pull-request#53]
Is it possible to create a PR with auto-merge option enabled? it's in beta now, docs are [here](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request)

**Comment by wei** [comment]
Thanks for the suggestion! 

It's not yet available through the API. We will need it to become available there then once our project dependency `hub` CLI adds it, we can easily include it as an option.

We can monitor the discussions there:
https://github.community/t/enabling-auto-merge-on-a-pr-using-the-api/150797?u=wei
https://github.community/t/enable-auto-merge-for-repository-via-api-v3/151331?u=wei

**Comment by dmitrysimkin** [comment]
@wei Potentially now possible as per https://github.community/t/enabling-auto-merge-on-a-pr-using-the-api/150797/5 ?

**Comment by wei** [comment]
It seems like it's only available over graphql api. https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge

We could use `hub api graphql` to make the request. PR welcome!

**Comment by waghanza** [comment]
Could you explain a little bit @wei ? What is `hub` ?

**Comment by wei** [comment]
@waghanza sure, it's https://hub.github.com/

**Comment by waghanza** [comment]
You mean this action could use a cli tool ?

**Comment by wei** [comment]
@waghanza it already does : )

**Comment by maxisam** [comment]
Have you thought about moving to https://cli.github.com/?

with gh you can use

```sh
gh pr merge --auto
``` 

https://github.com/cli/cli/issues/2619#issuecomment-976452610

**Comment by wei** [comment]
It will result in a rewrite which may affect backwards compatibility. Ideally hub should support this too if gh already does.

**Comment by maxisam** [comment]
Well, I doubt if they will keep support hub for long. It doesn't make too much sense to maintain 2 tools doing the same job
