### ISSUE TITLE
Create Setting for Output Verbosity and Better Echo's for Debugging

### ISSUE THREAD

**Issue by SionAbes** [repo-sync/pull-request#58]
Firstly, thanks guys and girls for this action. Been really enjoying using it! Just a small request: when trying to work out what went wrong during implementation the verbosity from the following line, made it very difficult to find out what was going on.

https://github.com/repo-sync/pull-request/blob/65194d8015be7624d231796ddee1cd52a5023cb3/entrypoint.sh#L29

Can I suggest an optional flag here?

Can I also suggest an echo within the following if clause: It just makes debugging a great deal easier!

https://github.com/repo-sync/pull-request/blob/65194d8015be7624d231796ddee1cd52a5023cb3/entrypoint.sh#L89-L91

**Comment by wei** [comment]
Good suggestions! PR welcome.

**Comment by wei** [comment]
Resolved in #58.
