### ISSUE TITLE
Is it possible to get the existing PR's ID and URLs?

### ISSUE THREAD

**Issue by antifuchs** [repo-sync/pull-request#62]
I've got an interesting problem: I would like an automated process that creates PRs from one long-lived branch to another, where one PR might on occasion contain multiple changes. To help reference the changes rolled up in these PRs, I'd like to leave a comment on the existing PR.

To that end, it would be really cool if `repo-sync/pull-request` could find & set the existing pull request's ID/URL in output in the "fails silently if the PR already exists" case.

Currently, I have this change: https://github.com/antifuchs/test_repo_for_production_branch/commit/d5e0535a5e63536885a74b207804782c71640c18, which results in [this output](https://github.com/antifuchs/test_repo_for_production_branch/runs/2784212177?check_suite_focus=true#step:5:3). I would love to have to not have to replicate a large part of this action's logic in order to get at that information!

**Comment by wei** [comment]
Good idea. PR Welcome!

**Comment by hpdobrica** [comment]
Hey @wei @antifuchs, I submitted a PR #114 dealing with this, can you guys please review?

**Comment by wei** [comment]
This was resolved in #117 ~
