### ISSUE TITLE
can destination_branch works with regex ?

### ISSUE THREAD

**Issue by arieIron** [repo-sync/pull-request#63]
I tried like this `destination_branch: '${{env.GIT_BRANCH_NAME}}*'` but got this error: `fatal: bad revision 'release-v1*'`
${{env.GIT_BRANCH_NAME}} = release-v1
I'm looking to get destination branch that name is 'release-v1.1'

**Comment by wei** [comment]
I don't think Git allows it. This is a git limitation.

**Comment by arieIron** [comment]
you can make it like this `echo $COMMIT_BRANCH | grep -E "^(\d\.?)+$"`

**Comment by wei** [comment]
Please try writing a custom action for your workflow.
