### ISSUE TITLE
Is their a way to configure the PR author

### ISSUE THREAD

**Issue by jamesrweb** [repo-sync/pull-request#65]
Right now we use this action internally on a repo to test how it works but we noticed that the person who pushes the code is not the PR author once it is generated, instead that will be the person who the GITHUB_TOKEN belongs to. How can we make the person who pushed the code the author of the PR also?

**Comment by wei** [comment]
I think it's a security limitation by GitHub. You could use assignee feature on the PR.

**Comment by jamesrweb** [comment]
We do this but the issue is that your PRs don't get shown as "contributions" in the graph, nor do they appear on the [pulls page](https://github.com/pulls) without manually moving filter to "assigned" but you would expect to be on the first "created" page.. I think this is something which should be looked into please because it's definitely an issue IMO.

**Comment by wei** [comment]
The only solution I can think of is to ask everyone to create a personal access token (PAT) and add logic in your code to pick the right one based on the committers on the pull request.

GitHub Action doesn't have access to make pull request on behalf of another user without a PAT.
