### ISSUE TITLE
Team_reviewer is throwing a HTTP 422 error

### ISSUE THREAD

**Issue by EmiiFont** [repo-sync/pull-request#68]
Hi, i'm trying to add the team as a reviewer but is not picking it up

I've tried `pr_reviewer: "team-prs"` `pr_reviewer: "/team-prs"` `pr_reviewer: "@org/team-prs"` `pr_reviewer: "org/team-prs"`

and it shows an error `Error requesting reviewer: Unprocessable Entity (HTTP 422)`

any ideas?

**Comment by wei** [comment]
Try to use a PAT with admin:org(read:org) scope

See https://github.community/t/bug-github-action-cannot-assign-teams/131186
