### ISSUE TITLE
fatal: bad revision 'master' when using distribution branch 'develop'

### ISSUE THREAD

**Issue by ns-ggeorgiev** [repo-sync/pull-request#77]
Hi,

I am getting fatal: bad revision 'master' even I have distribution branch set to 'develop', I am using v2.6.1. 

Where is this coming from?

From https://github.com/netSkope/ep-versioner
 + 3[7](https://github.com/netSkope/ep-versioner/runs/5258326895?check_suite_focus=true#step:11:7)07dc4...7[8](https://github.com/netSkope/ep-versioner/runs/5258326895?check_suite_focus=true#step:11:8)10b7e develop    -> develop  (forced update)
 * [new branch]      update_repo_enrichment@355fdb36aabe784b27eb7e05015f365e[9](https://github.com/netSkope/ep-versioner/runs/5258326895?check_suite_focus=true#step:11:9)04b153a -> update_repo_enrichment@355fdb36aabe784b27eb7e05015f365e904b153a
 * [new branch]      update_repo_enrichment@355fdb36aabe784b27eb7e05015f365e904b153a -> origin/update_repo_enrichment@355fdb36aabe784b27eb7e05015f365e904b153a
 * [new tag]         v0.0.2     -> v0.0.2
 * [new tag]         v0.0.3     -> v0.0.3
 * [new tag]         v0.1.0     -> v0.1.0
  develop                                                                        78[10](https://github.com/netSkope/ep-versioner/runs/5258326895?check_suite_focus=true#step:11:10)b7e [origin/develop] EP-[11](https://github.com/netSkope/ep-versioner/runs/5258326895?check_suite_focus=true#step:11:11)524: Update repo enrichments to 9cefce348cb5eafa5f95ca6fbec3cb93102f504b (#26)
  update_repo_enrichment@355fdb36aabe784b27eb7e050[15](https://github.com/netSkope/ep-versioner/runs/5258326895?check_suite_focus=true#step:11:15)f365e904b153a                0622028 EP-11524: Update repo enrichments to 355fdb36aabe784b27eb7e05015f365e904b153a
* update_repo_enrichment@79100a1e7a1e303d0459cf2d33bfb83f1d6ddaa4                3707dc4 [origin/update_repo_enrichment@79100a1e7a1e303d0459cf2d33bfb83f1d6ddaa4] EP-11524: Update repo enrichments to 79100a1e7a1e303d0459cf2d33bfb83f1d6ddaa4
  remotes/origin/develop                                                         7810b7e EP-11524: Update repo enrichments to 9cefce348cb5eafa5f95ca6fbec3cb93102f504b (#26)
  remotes/origin/update_repo_enrichment@355fdb36aabe784b27eb7e05015f365e904b153a 0622028 EP-11524: Update repo enrichments to 355fdb36aabe784b27eb7e05015f365e904b153a
  remotes/origin/update_repo_enrichment@79100a1e7a1e303d0459cf2d33bfb83f1d6ddaa4 3707dc4 EP-11524: Update repo enrichments to 79100a1e7a1e303d0459cf2d33bfb83f1d6ddaa4
fatal: bad revision 'master'

**Comment by wei** [comment]
It's destination branch not distribution branch~

**Comment by EhsanHerai** [comment]
@wei I'm using `destination_branch` but still have the same issue

**Comment by EhsanHerai** [comment]
oh my mistake.
I should use `${{ env.DESTINATION_BRANCH }}` not `${{ github.env.DESTINATION_BRANCH }}`
