### ISSUE TITLE
PR URL output

### ISSUE THREAD

**Issue by botnerd** [repo-sync/pull-request#8]
I have a use case where I need the PR URL for a subsequent steps in the workflow, but I cannot find any actions that provide that as an output. Would it be possible to provide the URL of the PR as an output from the action?

**Comment by jamesnetherton** [comment]
This would also be quite useful for me too. If you want to do follow on actions on the created PR, it's a bit tricky at the moment without the URL.

**Comment by wei** [comment]
Sounds like a good idea, PR welcome!

**Comment by wei** [comment]
Thanks @jamesnetherton for your contribution, this has been published and accessible via `repo-sync/pull-request@master`, `repo-sync/pull-request@v2` or `repo-sync/pull-request@v2.1`
