### ISSUE TITLE
Line break with checkboxes

### ISSUE THREAD

**Issue by yceballost** [repo-sync/pull-request#83]
Hi guys

How can I force a line break to get this 

> My text and then my checkbox
> - [ ] my checkbox

I was trying with `\` with `<br/>` but I can't generate a proper line break that render a checkbox

My results:
with `\`
![image](https://user-images.githubusercontent.com/6722153/162528762-55f43f16-5524-4d99-94fd-c33577cddce2.png)

with `<br/>`
![image](https://user-images.githubusercontent.com/6722153/162528802-5ee15996-5606-4a7c-8699-056c6e65187e.png)

thanks for the action! <3

**Comment by wei** [comment]
This might be related to https://github.com/repo-sync/pull-request/issues/27 PR Welcome!

**Comment by wei** [comment]
This will be tracked in #103

**Comment by yceballost** [comment]
Sorry!, I forgot add the solution to this issue!

I solved using `n\`

**Comment by wei** [comment]
Very nice! Thanks for the example!
