### ISSUE TITLE
Action succeeds if PR creation fails

### ISSUE THREAD

**Issue by ThijsBroersen** [repo-sync/pull-request#94]
I discovered that when e.g. GitHub API is not available this action still succeeds, should it?

Related line is prob: https://github.com/repo-sync/pull-request/blob/ff8726ae82c9970bde6527e419133aa167297c40/entrypoint.sh#L87

**Comment by wei** [comment]
It's current there to prevent throwing errors like 
![image](https://user-images.githubusercontent.com/5880908/199113891-bb437545-720b-4563-b193-c08ae3f2364e.png)

which doesn't really require user intervention. Ideas welcome.

**Comment by wei** [comment]
#62 will likely fix this. We can discuss more there.
