### ISSUE TITLE
Detect PR title to use from first commit message

### ISSUE THREAD

**Issue by privatenumber** [repo-sync/pull-request#97]
## Feature request
An option to auto populate the PR title and body to the first commit message and description, respectively.

## Motivation
When squashing PRs, there's a good chance we want to use the commit message at the PR title.

This is how GitHub.com's pull request creation UI behaves.

**Comment by wei** [comment]
Good idea. PR Welcome!

**Comment by heiskr** [comment]
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.
