### ISSUE TITLE
use `head_branch` and `base_branch` instead of `source_branch` and `destination_branch`

### ISSUE THREAD

**Issue by mmkal** [repo-sync/pull-request#99]
This would match GitHub's terminology and be less confusing ("source" and "destination" depend on your perspective, where `head` and `base` directly correspond to what will happen in the pull request)

(Hi! I like this action!)

**Comment by wei** [comment]
Good idea, we can make it backwards compatible. PR Welcome!

**Comment by heiskr** [comment]
Thank you for opening this issue. Per the updated README, we are in process of archiving this repository, and encourage using [`gh pr create`](https://cli.github.com/manual/gh_pr_create) directly in your workflows instead.
